# BÀI 1: LÀM QUEN VỚI PYTHON

## Bài tập thực hành

### Bài 1. Tạo Tensor cơ bản

In [1]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


#### Kích thước: torch.Size([2, 3]) (gồm 2 hàng và 3 cột)
#### Số chiều: 2
#### Kiểu dữ liệu: torch.int32 (số nguyên 32-bit)

### Bài 2. Tạo các Tensor thường dùng

In [2]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.0637, 0.0356, 0.5211, 0.4321],
        [0.6186, 0.5196, 0.0744, 0.9128],
        [0.6263, 0.2923, 0.0720, 0.3797]])
tensor([[ 0.8563, -1.1087, -1.4267,  0.3783],
        [-1.2043,  0.4415,  0.5518, -1.1317],
        [ 0.8823,  1.2803, -0.6109, -2.3636]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


#### Sự khác nhau giữa torch.rand() và torch.randn():
torch.rand(*size):
- Phân phối: Phân phối đều.
- Khoảng giá trị: Các số ngẫu nhiên được sinh ra nằm trong khoảng đều từ [0, 1) (từ 0 đến gần bằng 1).
- Ứng dụng: Thường dùng khi bạn cần khởi tạo các giá trị ngẫu nhiên có trọng số hoặc tỉ lệ phân bố đồng đều trong một khoảng giới hạn.
torch.randn(*size):
- Phân phối: Phân phối chuẩn.
- Khoảng giá trị: Các số ngẫu nhiên có giá trị trung bình (mean) bằng 0 và độ lệch chuẩn (standard deviation) bằng 1. Các giá trị tập trung nhiều quanh số 0, có thể có giá trị âm hoặc dương (vượt quá khoảng $[0, 1)$).
- Ứng dụng: Rất phổ biến trong Deep Learning để khởi tạo trọng số (weights) cho mạng neural hoặc tạo nhiễu.


### Tạo Tensor 5 x 5 chứa toàn giá trị 10

In [3]:
import torch

b = torch.full((5, 5), 10)

print(b)
print("Shape:", b.shape)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])
Shape: torch.Size([5, 5])


### Bài 3. Kiểm tra thông tin Tensor

In [4]:
import torch
a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


Trong PyTorch, torch.Size([2, 3, 4]) đại diện cho kích thước (shape) của một Tensor 3 chiều (3D Tensor).
- Chiều 0 (Dimension 0 - Trục 0): Có 2 mảng/ma trận 2D ở lớp ngoài cùng.
- Chiều 1 (Dimension 1 - Trục 1): Mỗi ma trận 2D đó bao gồm 3 dòng (rows).
- Chiều 2 (Dimension 2 - Trục 2): Mỗi dòng chứa 4 cột (columns).

### Bài 4. Slicing và Indexing

In [5]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[ 0.0193, -0.0310,  0.2545,  0.0816,  1.1805],
         [ 1.0449, -0.9946, -1.2440,  1.9153,  0.1989],
         [ 1.6022, -0.0302,  1.3629, -0.3131, -0.1362],
         [ 0.0797,  0.0045, -1.2942,  0.6631, -0.3200]],

        [[ 1.5883,  0.1104,  1.3247,  1.6236, -1.5374],
         [-0.7979, -0.8160, -1.8800,  0.8819, -0.1365],
         [-1.3830,  0.1482, -0.3669,  0.8270, -2.1453],
         [ 1.3379,  0.0328,  0.6738, -0.3816,  1.2390]],

        [[ 1.3101, -0.8030,  0.8693, -1.0442, -1.1029],
         [-0.1383, -0.4772,  0.5931, -0.0126,  0.2179],
         [ 0.9765, -1.9492, -0.7025, -0.9132,  0.1257],
         [ 1.3696, -0.6103, -0.8599, -0.1446, -0.2707]]])

Tensor a[1]:
tensor([[ 1.5883,  0.1104,  1.3247,  1.6236, -1.5374],
        [-0.7979, -0.8160, -1.8800,  0.8819, -0.1365],
        [-1.3830,  0.1482, -0.3669,  0.8270, -2.1453],
        [ 1.3379,  0.0328,  0.6738, -0.3816,  1.2390]])

Tensor a[1:, 2:4]:
tensor([[[-1.3830,  0.1482, -0.3669,  0.8270, -2.1

Kích thước (Shape) của các Tensor con: 
- Shape của a[1]: torch.Size([4, 5])
- Shape của a[1:, 2:4]: torch.Size([2, 2, 5])

### Thao tác lấy hai phần tử cuối cùng trên chiều thứ ba

In [6]:
sub_a = a[:, :, -2:]

print("Tensor mới chứa 2 phần tử cuối trên chiều thứ ba:")
print(sub_a)
print("Shape mới:", sub_a.shape)

Tensor mới chứa 2 phần tử cuối trên chiều thứ ba:
tensor([[[ 0.0816,  1.1805],
         [ 1.9153,  0.1989],
         [-0.3131, -0.1362],
         [ 0.6631, -0.3200]],

        [[ 1.6236, -1.5374],
         [ 0.8819, -0.1365],
         [ 0.8270, -2.1453],
         [-0.3816,  1.2390]],

        [[-1.0442, -1.1029],
         [-0.0126,  0.2179],
         [-0.9132,  0.1257],
         [-0.1446, -0.2707]]])
Shape mới: torch.Size([3, 4, 2])


### Bài 5. Reshape và Flatten

In [ ]:
import torch
a = torch.randn(3, 4)

print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[-0.8796,  0.2183, -0.5581, -0.3690],
        [-0.8209, -0.2615, -0.7864,  0.7828],
        [-2.0354, -0.6269,  0.3463,  0.2354]])

Flatten:
tensor([-0.8796,  0.2183, -0.5581, -0.3690, -0.8209, -0.2615, -0.7864,  0.7828,
        -2.0354, -0.6269,  0.3463,  0.2354])

Reshape to 3 x 2 x 2:
tensor([[[-0.8796,  0.2183],
         [-0.5581, -0.3690]],

        [[-0.8209, -0.2615],
         [-0.7864,  0.7828]],

        [[-2.0354, -0.6269],
         [ 0.3463,  0.2354]]])


### Kiểm tra số phần tử trước và sau khi reshape

In [8]:
num_before = a.numel()
num_after_ravel = a.ravel().numel()
num_after_reshape = a.reshape(3, 2, 2).numel()

print(f"Số phần tử ban đầu (3x4): {num_before}")
print(f"Số phần tử sau khi ravel(): {num_after_ravel}")
print(f"Số phần tử sau khi reshape(3, 2, 2): {num_after_reshape}")

Số phần tử ban đầu (3x4): 12
Số phần tử sau khi ravel(): 12
Số phần tử sau khi reshape(3, 2, 2): 12


### Thử reshape Tensor thành kích thước 2 × 6

In [9]:
b = a.reshape(2, 6)

print("Tensor sau khi reshape thành 2 x 6:")
print(b)
print("Shape mới:", b.shape)

Tensor sau khi reshape thành 2 x 6:
tensor([[-0.8796,  0.2183, -0.5581, -0.3690, -0.8209, -0.2615],
        [-0.7864,  0.7828, -2.0354, -0.6269,  0.3463,  0.2354]])
Shape mới: torch.Size([2, 6])
