# BÀI 1: LÀM QUEN VỚI PYTHON

## Bài tập thực hành

### Bài 1. Tạo Tensor cơ bản

In [1]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


#### Kích thước: torch.Size([2, 3]) (gồm 2 hàng và 3 cột)
#### Số chiều: 2
#### Kiểu dữ liệu: torch.int32 (số nguyên 32-bit)

### Bài 2. Tạo các Tensor thường dùng

In [2]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.0637, 0.0356, 0.5211, 0.4321],
        [0.6186, 0.5196, 0.0744, 0.9128],
        [0.6263, 0.2923, 0.0720, 0.3797]])
tensor([[ 0.8563, -1.1087, -1.4267,  0.3783],
        [-1.2043,  0.4415,  0.5518, -1.1317],
        [ 0.8823,  1.2803, -0.6109, -2.3636]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


#### Sự khác nhau giữa torch.rand() và torch.randn():
torch.rand(*size):
- Phân phối: Phân phối đều.
- Khoảng giá trị: Các số ngẫu nhiên được sinh ra nằm trong khoảng đều từ [0, 1) (từ 0 đến gần bằng 1).
- Ứng dụng: Thường dùng khi bạn cần khởi tạo các giá trị ngẫu nhiên có trọng số hoặc tỉ lệ phân bố đồng đều trong một khoảng giới hạn.
torch.randn(*size):
- Phân phối: Phân phối chuẩn.
- Khoảng giá trị: Các số ngẫu nhiên có giá trị trung bình (mean) bằng 0 và độ lệch chuẩn (standard deviation) bằng 1. Các giá trị tập trung nhiều quanh số 0, có thể có giá trị âm hoặc dương (vượt quá khoảng $[0, 1)$).
- Ứng dụng: Rất phổ biến trong Deep Learning để khởi tạo trọng số (weights) cho mạng neural hoặc tạo nhiễu.


### Tạo Tensor 5 x 5 chứa toàn giá trị 10

In [3]:
import torch

b = torch.full((5, 5), 10)

print(b)
print("Shape:", b.shape)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])
Shape: torch.Size([5, 5])


### Bài 3. Kiểm tra thông tin Tensor

In [4]:
import torch
a = torch.zeros(2, 3, 4)

print("Tensor:")
print(a)
print("Shape:", a.shape)
print("Size:", a.size())
print("Number of dimensions:", a.ndim)
print("Data type:", a.dtype)

Tensor:
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
Shape: torch.Size([2, 3, 4])
Size: torch.Size([2, 3, 4])
Number of dimensions: 3
Data type: torch.float32


Trong PyTorch, torch.Size([2, 3, 4]) đại diện cho kích thước (shape) của một Tensor 3 chiều (3D Tensor).
- Chiều 0 (Dimension 0 - Trục 0): Có 2 mảng/ma trận 2D ở lớp ngoài cùng.
- Chiều 1 (Dimension 1 - Trục 1): Mỗi ma trận 2D đó bao gồm 3 dòng (rows).
- Chiều 2 (Dimension 2 - Trục 2): Mỗi dòng chứa 4 cột (columns).

### Bài 4. Slicing và Indexing

In [5]:
import torch
a = torch.randn(3, 4, 5)
print("Original tensor:")
print(a)
print("\nTensor a[1]:")
print(a[1])
print("\nTensor a[1:, 2:4]:")
print(a[1:, 2:4])

Original tensor:
tensor([[[ 0.0193, -0.0310,  0.2545,  0.0816,  1.1805],
         [ 1.0449, -0.9946, -1.2440,  1.9153,  0.1989],
         [ 1.6022, -0.0302,  1.3629, -0.3131, -0.1362],
         [ 0.0797,  0.0045, -1.2942,  0.6631, -0.3200]],

        [[ 1.5883,  0.1104,  1.3247,  1.6236, -1.5374],
         [-0.7979, -0.8160, -1.8800,  0.8819, -0.1365],
         [-1.3830,  0.1482, -0.3669,  0.8270, -2.1453],
         [ 1.3379,  0.0328,  0.6738, -0.3816,  1.2390]],

        [[ 1.3101, -0.8030,  0.8693, -1.0442, -1.1029],
         [-0.1383, -0.4772,  0.5931, -0.0126,  0.2179],
         [ 0.9765, -1.9492, -0.7025, -0.9132,  0.1257],
         [ 1.3696, -0.6103, -0.8599, -0.1446, -0.2707]]])

Tensor a[1]:
tensor([[ 1.5883,  0.1104,  1.3247,  1.6236, -1.5374],
        [-0.7979, -0.8160, -1.8800,  0.8819, -0.1365],
        [-1.3830,  0.1482, -0.3669,  0.8270, -2.1453],
        [ 1.3379,  0.0328,  0.6738, -0.3816,  1.2390]])

Tensor a[1:, 2:4]:
tensor([[[-1.3830,  0.1482, -0.3669,  0.8270, -2.1

Kích thước (Shape) của các Tensor con: 
- Shape của a[1]: torch.Size([4, 5])
- Shape của a[1:, 2:4]: torch.Size([2, 2, 5])

### Thao tác lấy hai phần tử cuối cùng trên chiều thứ ba

In [6]:
sub_a = a[:, :, -2:]

print("Tensor mới chứa 2 phần tử cuối trên chiều thứ ba:")
print(sub_a)
print("Shape mới:", sub_a.shape)

Tensor mới chứa 2 phần tử cuối trên chiều thứ ba:
tensor([[[ 0.0816,  1.1805],
         [ 1.9153,  0.1989],
         [-0.3131, -0.1362],
         [ 0.6631, -0.3200]],

        [[ 1.6236, -1.5374],
         [ 0.8819, -0.1365],
         [ 0.8270, -2.1453],
         [-0.3816,  1.2390]],

        [[-1.0442, -1.1029],
         [-0.0126,  0.2179],
         [-0.9132,  0.1257],
         [-0.1446, -0.2707]]])
Shape mới: torch.Size([3, 4, 2])


### Bài 5. Reshape và Flatten

In [ ]:
import torch
a = torch.randn(3, 4)

print("Original:")
print(a)
print("\nFlatten:")
print(a.ravel())
print("\nReshape to 3 x 2 x 2:")
print(a.reshape(3, 2, 2))

Original:
tensor([[-0.8796,  0.2183, -0.5581, -0.3690],
        [-0.8209, -0.2615, -0.7864,  0.7828],
        [-2.0354, -0.6269,  0.3463,  0.2354]])

Flatten:
tensor([-0.8796,  0.2183, -0.5581, -0.3690, -0.8209, -0.2615, -0.7864,  0.7828,
        -2.0354, -0.6269,  0.3463,  0.2354])

Reshape to 3 x 2 x 2:
tensor([[[-0.8796,  0.2183],
         [-0.5581, -0.3690]],

        [[-0.8209, -0.2615],
         [-0.7864,  0.7828]],

        [[-2.0354, -0.6269],
         [ 0.3463,  0.2354]]])


### Kiểm tra số phần tử trước và sau khi reshape

In [8]:
num_before = a.numel()
num_after_ravel = a.ravel().numel()
num_after_reshape = a.reshape(3, 2, 2).numel()

print(f"Số phần tử ban đầu (3x4): {num_before}")
print(f"Số phần tử sau khi ravel(): {num_after_ravel}")
print(f"Số phần tử sau khi reshape(3, 2, 2): {num_after_reshape}")

Số phần tử ban đầu (3x4): 12
Số phần tử sau khi ravel(): 12
Số phần tử sau khi reshape(3, 2, 2): 12


### Thử reshape Tensor thành kích thước 2 × 6

In [9]:
b = a.reshape(2, 6)

print("Tensor sau khi reshape thành 2 x 6:")
print(b)
print("Shape mới:", b.shape)

Tensor sau khi reshape thành 2 x 6:
tensor([[-0.8796,  0.2183, -0.5581, -0.3690, -0.8209, -0.2615],
        [-0.7864,  0.7828, -2.0354, -0.6269,  0.3463,  0.2354]])
Shape mới: torch.Size([2, 6])


### Bài 6. Phép toán và nhân ma trận

In [10]:
import torch
a = torch.randn(2, 3)
b = torch.randn(2, 3)

print("a:")
print(a)
print("b:")
print(b)
print("\na + b:")
print(a + b)
print("\na / b:")
print(a / b)
print("\na^2:")
print(a ** 2)
print("\nMatrix multiplication:")
print(a @ b.T)

a:
tensor([[ 0.8538,  0.3369,  0.5387],
        [ 1.8936,  0.3462, -0.1484]])
b:
tensor([[-0.6578,  0.0368,  1.0458],
        [ 0.5855,  0.8771,  0.3114]])

a + b:
tensor([[0.1959, 0.3737, 1.5845],
        [2.4791, 1.2232, 0.1631]])

a / b:
tensor([[-1.2979,  9.1481,  0.5151],
        [ 3.2343,  0.3947, -0.4764]])

a^2:
tensor([[0.7289, 0.1135, 0.2902],
        [3.5859, 0.1198, 0.0220]])

Matrix multiplication:
tensor([[ 0.0142,  0.9631],
        [-1.3881,  1.3661]])


Phân biệt phép toán a * b và a @ b.T:
Phép toán a * b:
- Cơ chế: Nhân từng phần tử tương ứng (element-by-element) của Tensor a với Tensor b.
- Yêu cầu: a và b phải cùng kích thước.
- Kết quả: Trả về một Tensor mới có cùng kích thước ban đầu.
Phép toán a @ b.T:
- Cơ chế: Phép nhân ma trận đại số tuyến tính.
- Yêu cầu: Số cột của ma trận thứ nhất phải bằng số hàng của ma trận thứ hai. Với a (2 x 3) và b.T (3 x 2), phép nhân hợp lệ vì chiều trong trùng nhau (3 = 3).
- Kết quả: Trả về một ma trận tích theo quy tắc đại số.

Kích thước (Shape) của kết quả a @ b.T:
- Shape kết quả: torch.Size([2, 2])

### Bài 7. Các hàm thống kê trên Tensor

In [1]:
import torch
a = torch.randn(3, 4)
print(a)
print("\nMean:")
print(torch.mean(a, dim=0))
print("\nStandard deviation:")
print(torch.std(a, dim=0))
print("\nCumulative sum:")
print(torch.cumsum(a, dim=0))

tensor([[ 1.5531,  0.5392,  0.7522,  0.3929],
        [ 1.1815,  0.7272, -0.2647, -0.8271],
        [-0.0464, -0.4368, -0.4179, -0.0280]])

Mean:
tensor([ 0.8961,  0.2765,  0.0232, -0.1541])

Standard deviation:
tensor([0.8371, 0.6249, 0.6360, 0.6197])

Cumulative sum:
tensor([[ 1.5531,  0.5392,  0.7522,  0.3929],
        [ 2.7346,  1.2664,  0.4875, -0.4342],
        [ 2.6882,  0.8296,  0.0696, -0.4622]])


Thay dim=0 bằng dim=1 và nhận xét sự khác nhau:
Khi dùng dim=0:
- Hướng thực thi: Thao tác dọc (chiều dọc theo 3 hàng).
- Giá trị trung bình (mean): Tính trung bình của từng cột.
- Độ lệch chuẩn (std): Tính độ lệch chuẩn của từng cột.
- Tổng tích lũy (cumsum): Cộng dồn từ hàng 0 xuống hàng 2.
Khi dùng dim=1:
- Hướng thực thi: Thao tác ngang (chiều ngang theo 4 cột).
- Giá trị trung bình (mean): Tính trung bình của từng hàng.
- Độ lệch chuẩn (std): Tính độ lệch chuẩn của từng hàng.
- Tổng tích lũy (cumsum): Cộng dồn từ cột 0 sang cột 3.

### Bài 8. Autograd cơ bản

In [2]:
import torch
x = torch.tensor(
3.6,
requires_grad=True
)
y = x * x
y.backward()
print("x =", x)
print("y =", y)
print("x.grad =", x.grad)

x = tensor(3.6000, requires_grad=True)
y = tensor(12.9600, grad_fn=<MulBackward0>)
x.grad = tensor(7.2000)


Tính thủ công đạo hàm của y = x2 tại x = 3.6 và so sánh với x.grad.

In [3]:
import torch

x = torch.tensor(3.6, requires_grad=True)
y = x**2
y.backward()

print("x.grad:", x.grad.item())  # Kết quả: 7.2

x.grad: 7.199999809265137


Đổi hàm thành y = 3*x**2 + 2*x + 1 và kiểm tra gradient.

In [4]:
import torch

x = torch.tensor(3.6, requires_grad=True)
y = 3 * x**2 + 2 * x + 1
y.backward()

print("x.grad:", x.grad.item())  # Kết quả: 23.6

x.grad: 23.599998474121094


### Bài 9. Gradient Descent tìm hệ số đa thức

In [6]:
import numpy as np
import torch
polynomial = np.poly1d([1, 2, 3])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)
XX = np.hstack([
X * X,
X,
np.ones_like(X)
])
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)
optimizer = torch.optim.NAdam([w], lr=0.01)
print("Initial coefficients:")
print(w)
for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()
print("Learned coefficients:")
print(w)

Initial coefficients:
tensor([[-0.1035],
        [-0.1554],
        [ 0.9400]], requires_grad=True)
Learned coefficients:
tensor([[1.0067],
        [2.0048],
        [2.5245]], requires_grad=True)


So sánh ba hệ số học được với [1, 2, 3]:
- Ba hệ số học được trong w sẽ gần như trùng khớp hoàn toàn với [[1.], [2.], [3.]] (hoặc chênh lệch cực kỳ nhỏ do sai số số thực float32).
Giải thích vai trò của optimizer.zero_grad(), mse.backward() và optimizer.step():
- optimizer.zero_grad(): Xóa các giá trị đạo hàm (gradient) đã lưu ở vòng lặp trước trong biến w.grad. Trong PyTorch, gradient mặc định sẽ cộng dồn (accumulate) qua mỗi lần gọi .backward(). Nếu không xóa, gradient mới sẽ cộng thêm vào gradient cũ khiến bước cập nhật trọng số bị sai hướng.
- mse.backward(): Thực hiện thuật toán lan truyền ngược (Backpropagation). Lệnh này tính đạo hàm riêng của hàm mất mát mse theo biến trọng số w và lưu kết quả đó vào thuộc tính w.grad.
- optimizer.step(): Thực hiện cập nhật trọng số w dựa trên gradient vừa tính được (w.grad) và thuật toán tối ưu NAdam cùng với tốc độ học lr=0.01.

### Bài 10. Giải hệ phương trình bằng Autograd

In [7]:
import random
import torch
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)
for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1*y1 + y2*y2 + y3*y3 + y4*y4
    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()
print("A =", A)
print("B =", B)

print("C =", C)
print("D =", D)

A = tensor(4.7802, requires_grad=True)
B = tensor(4.2197, requires_grad=True)
C = tensor(3.2198, requires_grad=True)
D = tensor(2.2197, requires_grad=True)


### Kiểm tra nghiệm thu được với bốn phương trình: A+B=9, C-D=1, A+C=8, B-D=2.

In [8]:
import random
import torch

# 1. Khởi tạo ngẫu nhiên
A = torch.tensor(random.random(), requires_grad=True)
B = torch.tensor(random.random(), requires_grad=True)
C = torch.tensor(random.random(), requires_grad=True)
D = torch.tensor(random.random(), requires_grad=True)

# 2. Huấn luyện bằng NAdam
EPOCHS = 2000
optimizer = torch.optim.NAdam([A, B, C, D], lr=0.01)

for _ in range(EPOCHS):
    y1 = A + B - 9
    y2 = C - D - 1
    y3 = A + C - 8
    y4 = B - D - 2
    sqerr = y1 * y1 + y2 * y2 + y3 * y3 + y4 * y4

    optimizer.zero_grad()
    sqerr.backward()
    optimizer.step()

# Lấy giá trị float từ tensor
a, b, c, d = A.item(), B.item(), C.item(), D.item()

# 3. In giá trị tìm được
print("=== NGHIỆM TÌM ĐƯỢC ===")
print(f"A = {a:.4f}, B = {b:.4f}, C = {c:.4f}, D = {d:.4f}\n")

# 4. Kiểm tra mức độ thỏa mãn các phương trình
print("=== KIỂM TRA VỚI 4 PHƯƠNG TRÌNH ===")
print(f"1) A + B = {a + b:.4f} (Mục tiêu: 9)")
print(f"2) C - D = {c - d:.4f} (Mục tiêu: 1)")
print(f"3) A + C = {a + c:.4f} (Mục tiêu: 8)")
print(f"4) B - D = {b - d:.4f} (Mục tiêu: 2)")

# 5. Kiểm tra tính đúng đắn theo dạng nghiệm tổng quát (7-t, t+2, t+1, t)
t = d
print("\n=== ĐỐI CHIẾU VỚI CÔNG THỨC NGHIỆM TỔNG QUÁT ===")
print(f"Nghiệm thực tế    : ({a:.4f}, {b:.4f}, {c:.4f}, {d:.4f})")
print(f"Nghiệm theo lý thuyết: ({7-t:.4f}, {t+2:.4f}, {t+1:.4f}, {t:.4f})")

=== NGHIỆM TÌM ĐƯỢC ===
A = 4.6186, B = 4.3813, C = 3.3814, D = 2.3813

=== KIỂM TRA VỚI 4 PHƯƠNG TRÌNH ===
1) A + B = 8.9999 (Mục tiêu: 9)
2) C - D = 1.0000 (Mục tiêu: 1)
3) A + C = 8.0000 (Mục tiêu: 8)
4) B - D = 2.0000 (Mục tiêu: 2)

=== ĐỐI CHIẾU VỚI CÔNG THỨC NGHIỆM TỔNG QUÁT ===
Nghiệm thực tế    : (4.6186, 4.3813, 3.3814, 2.3813)
Nghiệm theo lý thuyết: (4.6187, 4.3813, 3.3813, 2.3813)


### Bài 11. Viết chương trình PyTorch

#### Tạo và Reshape Tensor 24 phần tử

In [9]:
import torch

# Tạo Tensor X gồm 24 phần tử (từ 0 đến 23)
X = torch.arange(24)

# Reshape thành các kích thước yêu cầu
X_4x6 = X.reshape(4, 6)
X_2x12 = X.reshape(2, 12)
X_2x3x4 = X.reshape(2, 3, 4)

print("Kích thước 4x6:\n", X_4x6)
print("\nKích thước 2x12:\n", X_2x12)
print("\nKích thước 2x3x4:\n", X_2x3x4)

Kích thước 4x6:
 tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]])

Kích thước 2x12:
 tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

Kích thước 2x3x4:
 tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


#### Phép toán trên Tensor A và B (3 × 4)

In [10]:
import torch

torch.manual_seed(42)  # Cố định ngẫu nhiên để dễ đối chiếu
A = torch.randn(3, 4)
B = torch.randn(3, 4)

# Các phép toán phần tử (element-wise)
A_plus_B = A + B
A_mul_B = A * B
A_div_B = A / B

# Trung bình và độ lệch chuẩn theo cột (dim=0)
mean_A_col = torch.mean(A, dim=0)
std_A_col = torch.std(A, dim=0)

mean_B_col = torch.mean(B, dim=0)
std_B_col = torch.std(B, dim=0)

print("A + B:\n", A_plus_B)
print("\nA * B:\n", A_mul_B)
print("\nA / B:\n", A_div_B)
print("\nA - Trung bình theo cột:", mean_A_col)
print("A - Độ lệch chuẩn theo cột:", std_A_col)
print("\nB - Trung bình theo cột:", mean_B_col)
print("B - Độ lệch chuẩn theo cột:", std_B_col)

A + B:
 tensor([[ 1.4470, -1.5610, -0.7545,  1.1883],
        [ 0.1993,  0.6309,  1.4424, -1.3886],
        [ 1.8142,  0.9537,  0.2071,  1.6043]])

A * B:
 tensor([[ 0.3738, -0.2177, -0.2319,  0.2207],
        [-1.4846, -0.1523, -1.6911,  0.4789],
        [ 0.6244,  0.1835, -0.1753,  0.6434]])

A / B:
 tensor([[ 0.3032, -0.0762, -0.2371,  0.2404],
        [-0.8493, -0.2280, -2.8834,  0.8500],
        [ 0.3413,  0.3895, -1.6320,  1.0181]])

A - Trung bình theo cột: tensor([-0.1082,  0.0699,  0.9925,  0.1339])
A - Độ lệch chuẩn theo cột: tensor([0.8810, 0.2325, 1.0635, 0.7285])

B - Trung bình theo cột: tensor([ 1.2617, -0.0621, -0.6942,  0.3341])
B - Độ lệch chuẩn theo cột: tensor([0.1320, 1.4112, 0.3364, 0.9429])


#### Cho y = 2x2 + 5x + 3. Dùng autograd tính dy/dx tại x = 2 và kiểm tra bằng phép tính thủ công.

In [11]:
import torch

x = torch.tensor(2.0, requires_grad=True)
y = 2 * x**2 + 5 * x + 3
y.backward()

print("Kế quả từ PyTorch (x.grad):", x.grad.item())
print("Kết quả tính thủ công:", 4 * 2 + 5)

Kế quả từ PyTorch (x.grad): 13.0
Kết quả tính thủ công: 13


#### Thay đa thức trong Bài 9 bằng y = 2x2 - 3x + 5; huấn luyện và cho biết các hệ số tìm được.

In [12]:
import numpy as np
import torch

# 1. Tạo dữ liệu giả lập từ y = 2x^2 - 3x + 5
polynomial = np.poly1d([2, -3, 5])
N = 20
X = np.random.randn(N, 1) * 5
Y = polynomial(X)

# 2. Tạo ma trận đặc trưng [X^2, X, 1]
XX = np.hstack([X * X, X, np.ones_like(X)])

# 3. Khởi tạo trọng số ngẫu nhiên
w = torch.randn(3, 1, requires_grad=True)
x = torch.tensor(XX, dtype=torch.float32)
y = torch.tensor(Y, dtype=torch.float32)

# 4. Huấn luyện với NAdam
optimizer = torch.optim.NAdam([w], lr=0.01)

for epoch in range(1000):
    optimizer.zero_grad()
    y_pred = x @ w
    mse = torch.mean(torch.square(y - y_pred))
    mse.backward()
    optimizer.step()

print("Các hệ số tìm được (Learned coefficients):")
print(w.detach().numpy())

Các hệ số tìm được (Learned coefficients):
[[ 2.0316222]
 [-3.06812  ]
 [ 3.5583532]]


In [14]:
!jupyter nbconvert --to html lab1.ipynb

[NbConvertApp] Converting notebook lab1.ipynb to html
[NbConvertApp] Writing 384914 bytes to lab1.html


# Kết Thúc