# BÀI 1: LÀM QUEN VỚI PYTHON

## Bài tập thực hành

### Bài 1. Tạo Tensor cơ bản

In [1]:
import torch
a = torch.tensor(
[[1, 2, 3],
[4, 5, 6]],
dtype=torch.int32
)
print(a)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


#### Kích thước: torch.Size([2, 3]) (gồm 2 hàng và 3 cột)
#### Số chiều: 2
#### Kiểu dữ liệu: torch.int32 (số nguyên 32-bit)

### Bài 2. Tạo các Tensor thường dùng

In [2]:
import torch
a = torch.rand(3, 4)
b = torch.randn(3, 4)
c = torch.zeros(2, 3)
d = torch.ones(2, 3)
e = torch.eye(4)
print(a)
print(b)
print(c)
print(d)
print(e)

tensor([[0.0637, 0.0356, 0.5211, 0.4321],
        [0.6186, 0.5196, 0.0744, 0.9128],
        [0.6263, 0.2923, 0.0720, 0.3797]])
tensor([[ 0.8563, -1.1087, -1.4267,  0.3783],
        [-1.2043,  0.4415,  0.5518, -1.1317],
        [ 0.8823,  1.2803, -0.6109, -2.3636]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


#### Sự khác nhau giữa torch.rand() và torch.randn():
torch.rand(*size):
- Phân phối: Phân phối đều.
- Khoảng giá trị: Các số ngẫu nhiên được sinh ra nằm trong khoảng đều từ [0, 1) (từ 0 đến gần bằng 1).
- Ứng dụng: Thường dùng khi bạn cần khởi tạo các giá trị ngẫu nhiên có trọng số hoặc tỉ lệ phân bố đồng đều trong một khoảng giới hạn.
torch.randn(*size):
- Phân phối: Phân phối chuẩn.
- Khoảng giá trị: Các số ngẫu nhiên có giá trị trung bình (mean) bằng 0 và độ lệch chuẩn (standard deviation) bằng 1. Các giá trị tập trung nhiều quanh số 0, có thể có giá trị âm hoặc dương (vượt quá khoảng $[0, 1)$).
- Ứng dụng: Rất phổ biến trong Deep Learning để khởi tạo trọng số (weights) cho mạng neural hoặc tạo nhiễu.


### Tạo Tensor 5 x 5 chứa toàn giá trị 10

In [3]:
import torch

b = torch.full((5, 5), 10)

print(b)
print("Shape:", b.shape)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])
Shape: torch.Size([5, 5])
